runfile<<"eval `scramv1 runtime -csh`"<<endl;
runfile<<"tar -xzvf ../../tar_for_condor.tar"<<endl;
runfile<<"cd SusyNtuplizer/macro"<<endl;
runfile<<"echo \"Make BtagEff\""<<endl;
        runfile<<"root -l -b -q ana_MC_BTagEff_arg.C\\(\\\"${1}\\\",\\\"${2}\\\"\\)"<<endl;
runfile<<""<<endl;
runfile<<"echo \"do JEC+1\""<<endl;
runfile<<"sed -i 's/int bumpJEC = 0/int bumpJEC = 1/' params_arg.h #jec +1"<<endl;
        runfile<<"root -l -b -q ana_Main_MC_arg.C\\(\\\"${1}\\\",\\\"${2}\\\"\\)"<<endl;
        runfile<<"root -l -b -q postanaana_MC_arg.C+\\(\\\"${1}\\\"\\)"<<endl;
runfile<<"echo $3 >>foo; sed -i 's/.root/JECUp.root/' foo; set new_plotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $3 $new_plotsroot_mc"<<endl;
runfile<<"echo $4 >>foo; sed -i 's/.txt/JECUp.txt/' foo; set new_logplotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $4 $new_logplotsroot_mc"<<endl;
runfile<<"echo $5 >>foo; sed -i 's/.root/JECUp.root/' foo; set new_plotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $5 $new_plotsAndBackground_mc"<<endl;
runfile<<"echo $6 >>foo; sed -i 's/.txt/JECUp.txt/' foo; set new_logplotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $6 $new_logplotsAndBackground_mc"<<endl;
runfile<<"tar -cvf ${1}.tar new_plotsroot_mc new_logplotsroot_mc new_plotsAndBackground_mc new_logplotsAndBackground_mc"<<endl;
runfile<<""<<endl;
runfile<<"echo \"do JEC-1\""<<endl;
runfile<<"sed -i 's/int bumpJEC = 1/int bumpJEC = -1/' params_arg.h #jec -1"<<endl;
        runfile<<"root -l -b -q ana_Main_MC_arg.C\\(\\\"${1}\\\",\\\"${2}\\\"\\)"<<endl;
        runfile<<"root -l -b -q postanaana_MC_arg.C+\\(\\\"${1}\\\"\\)"<<endl;
runfile<<"echo $3 >>foo; sed -i 's/.root/JECDown.root/' foo; set new_plotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $3 $new_plotsroot_mc"<<endl;
runfile<<"echo $4 >>foo; sed -i 's/.txt/JECDown.txt/' foo; set new_logplotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $4 $new_logplotsroot_mc"<<endl;
runfile<<"echo $5 >>foo; sed -i 's/.root/JECDown.root/' foo; set new_plotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $5 $new_plotsAndBackground_mc"<<endl;
runfile<<"echo $6 >>foo; sed -i 's/.txt/JECDown.txt/' foo; set new_logplotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $6 $new_logplotsAndBackground_mc"<<endl;
runfile<<"tar -uvf ${1}.tar new_plotsroot_mc new_logplotsroot_mc new_plotsAndBackground_mc new_logplotsAndBackground_mc"<<endl;
runfile<<""<<endl;
runfile<<"echo \"do BtagEff+1\""<<endl;
runfile<<"sed -i 's/int bumpJEC = -1/int bumpJEC = 0/' params_arg.h"<<endl;
runfile<<"sed -i 's/int bumpBtagEff = 0/int bumpBtagEff = 1/' params_arg.h #btag +1"<<endl;
        runfile<<"root -l -b -q ana_Main_MC_arg.C\\(\\\"${1}\\\",\\\"${2}\\\"\\)"<<endl;
        runfile<<"root -l -b -q postanaana_MC_arg.C+\\(\\\"${1}\\\"\\)"<<endl;
runfile<<"echo $3 >>foo; sed -i 's/.root/BtagEffUp.root/' foo; set new_plotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $3 $new_plotsroot_mc"<<endl;
runfile<<"echo $4 >>foo; sed -i 's/.txt/BtagEffUp.txt/' foo; set new_logplotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $4 $new_logplotsroot_mc"<<endl;
runfile<<"echo $5 >>foo; sed -i 's/.root/BtagEffUp.root/' foo; set new_plotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $5 $new_plotsAndBackground_mc"<<endl;
runfile<<"echo $6 >>foo; sed -i 's/.txt/BtagEffUp.txt/' foo; set new_logplotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $6 $new_logplotsAndBackground_mc"<<endl;
runfile<<"tar -uvf ${1}.tar new_plotsroot_mc new_logplotsroot_mc new_plotsAndBackground_mc new_logplotsAndBackground_mc"<<endl;
runfile<<""<<endl;
runfile<<"echo \"do BtagEff-1\""<<endl;
runfile<<"sed -i 's/int bumpBtagEff = 1/int bumpBtagEff = -1/' params_arg.h #btag -1"<<endl;
        runfile<<"root -l -b -q ana_Main_MC_arg.C\\(\\\"${1}\\\",\\\"${2}\\\"\\)"<<endl;
        runfile<<"root -l -b -q postanaana_MC_arg.C+\\(\\\"${1}\\\"\\)"<<endl;
runfile<<"echo $3 >>foo; sed -i 's/.root/BtagEffDown.root/' foo; set new_plotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $3 $new_plotsroot_mc"<<endl;
runfile<<"echo $4 >>foo; sed -i 's/.txt/BtagEffDown.txt/' foo; set new_logplotsroot_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $4 $new_logplotsroot_mc"<<endl;
runfile<<"echo $5 >>foo; sed -i 's/.root/BtagEffDown.root/' foo; set new_plotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $5 $new_plotsAndBackground_mc"<<endl;
runfile<<"echo $6 >>foo; sed -i 's/.txt/BtagEffDown.txt/' foo; set new_logplotsAndBackground_mc = `cat foo`; rm foo"<<endl;
runfile<<"mv $6 $new_logplotsAndBackground_mc"<<endl;
runfile<<"tar -uvf ${1}.tar new_plotsroot_mc new_logplotsroot_mc new_plotsAndBackground_mc new_logplotsAndBackground_mc"<<endl;
runfile<<""<<endl;
runfile<<"echo \"do main\""<<endl;
runfile<<"sed -i 's/int bumpBtagEff = -1/int bumpBtagEff = 0/' params_arg.h #do normal"<<endl;
        runfile<<"root -l -b -q ana_Main_MC_arg.C\\(\\\"${1}\\\",\\\"${2}\\\"\\)"<<endl;
        runfile<<"root -l -b -q postanaana_MC_arg.C+\\(\\\"${1}\\\"\\)"<<endl;
runfile<<"tar -uvf ${1}.tar ${3} ${4} ${5} ${6}"<<endl;
runfile<<""<<endl;
runfile<<"mv ${1}.tar ../../../../"<<endl;
